apiVersion: v1
kind: Pod
metadata:
  name: ritesh
  labels:
    app: nginx
    rel: stable
spec:
  containers:
    - name: ritesh
      image: nginx:alpine
      ports:
        - containerPort: 80
# kubectl create -f .\pod.yml --save-config
# kubectl apply -f .\pod.yml
# kubectl exec ritesh -it sh
# kubectl edit -f .\pod.yml
# kubectl delete -f .\pod.yml
